
package com.ipartek.peliculas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PeliculasServiceWSImp", targetNamespace = "http://com.ipartek.formacion/types")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeliculasServiceWSImp {


    /**
     * 
     * @return
     *     returns com.ipartek.peliculas.PeliculaColeccionMensaje
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenertodos", targetNamespace = "http://com.ipartek.formacion/types", className = "com.ipartek.peliculas.Obtenertodos")
    @ResponseWrapper(localName = "obtenertodosResponse", targetNamespace = "http://com.ipartek.formacion/types", className = "com.ipartek.peliculas.ObtenertodosResponse")
    public PeliculaColeccionMensaje obtenertodos();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.peliculas.PeliculaMensaje
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerporid", targetNamespace = "http://com.ipartek.formacion/types", className = "com.ipartek.peliculas.Obtenerporid")
    @ResponseWrapper(localName = "obtenerporidResponse", targetNamespace = "http://com.ipartek.formacion/types", className = "com.ipartek.peliculas.ObtenerporidResponse")
    public PeliculaMensaje obtenerporid(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
